### ISSUE TITLE
NSUserDefaultsSettings.Factory hides ObservableSettings interface

### ISSUE THREAD

**Issue by svenjacobs** [russhwolf/multiplatform-settings#125]
I just started to integrate your library in a project. Thanks for the great work so far! 👏🏼 

However I noticed that when creating an `NSUserDefaultsSettings` instance through the factory, the factory returns the `Settings` interface although `NSUserDefaultsSettings` implements `ObservableSettings`. So for example when I want to convert the instance to `FlowSettings`, I currently have to write:

```kotlin
(NSUserDefaultsSettings.Factory().create() as ObservableSettings).toFlowSettings()
```

Any specific reason for that or is this just an oversight?

Version: 1.0.0-alpha01

**Comment by russhwolf** [comment]
It's because the `Factory` interface was originally designed to be cached in your common code when you might create multiple `Settings` instances. In that case, depending on what platforms you support, you might not be able to assume it's observable.

But I can see the usefulness of having individual factories output more specific types, so I'm happy to make that change ahead of 1.0. Feel free to open a PR, or else I'll get to it in the next week or two
