### ISSUE TITLE
Kotlin/Wasm

### ISSUE THREAD

**Issue by dbaroncelli** [russhwolf/multiplatform-settings#142]
Are there plans to implement the APIs also for Kotlin/Wasm?

**Comment by russhwolf** [comment]
I don't know the wasm space well enough to know if there's an obvious backing API to use. But at the very least, adding the interfaces would be easy enough and then it will be possible to pass your own implementation to try stuff out.

**Comment by dbaroncelli** [comment]
any update about the implementation for Wasm?

**Comment by esafak** [comment]
Could we take inspiration from [JuulLabs/indexeddb](https://github.com/JuulLabs/indexeddb)?

**Comment by eskatos** [comment]
For the browser target I assume localstorage would be a good choice.

**Comment by Ic-ks** [comment]
I forked and updated the project to work for target `wasm { browser() }`. I had to bump kotlin to 1.9.0, because wasm support for `kotlin.plugin.serialization` exists for 1.9.0 only (@see: jetbrains experimental wasm [repo](https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental)). Besides that it uses the same [implementation](https://github.com/russhwolf/multiplatform-settings/compare/main...Ic-ks:multiplatform-settings-wasm:main#diff-a042fe415bd4b12ca9c845af2e42b93fdd22fae2d821842523241adab03bfccd) of `localStorage` as JS does. The only difference is the prevented usage of `["key"]` calls which causes runtime exceptions (see: https://youtrack.jetbrains.com/issue/KT-59294). I can create a PR from these [changes](https://github.com/russhwolf/multiplatform-settings/compare/main...Ic-ks:multiplatform-settings-wasm:main#diff-a042fe415bd4b12ca9c845af2e42b93fdd22fae2d821842523241adab03bfccd) if there is interest?

**Comment by russhwolf** [comment]
I have a version of this I'm planning to release soon as part of version 1.1. I went a slightly different route than @Ic-ks by creating a shared js/wasm source-set since they're running the same implementation (this required a little bit of expect/actual typealiasing because Kotlin metadata doesn't know that these targets sharing dependencies, but it shouldn't break any existing js users).

Questions for people following this ticket:
1. Is the browser target sufficient for your needs? I don't know an implementation to use for node or d8, but maybe someone has suggestions. If it would be useful, I might be able to publish interfaces to those other targets even without shipping an implementation, but it's a bit of a pain for the same reason I never published anything for node in the js target.
2. Right now, I'm only adding wasm to the modules `multiplatform-settings`, `multiplatform-settings-test`, and `multiplatform-settings-no-arg`. I didn't add it to the coroutines or serialization modules to avoid needing to depend on the wasm-specific versions of those libraries. I'd prefer to keep to a single version of Multiplatform Settings rather than maintaining a separate wasm-specific version, but that makes depending on wasm-specific versions of other libraries more difficult. Let me know if you want these integrations on wasm, and if there's enough demand I may reconsider.

**Comment by eskatos** [comment]
The browser target with local storage would be enough for me.

The wasm-specific library versions are a pain but hopefully this will be solved relatively soon.

**Comment by russhwolf** [comment]
WASM browser support is now released in version 1.1.0.

**Comment by shriharsha-srb** [comment]
Does multiplatform-settings-serialization:1.1.1 support wasm target as well ?

**Comment by shriharsha-srb** [comment]
@russhwolf  Does multiplatform-settings-serialization:1.1.1 support wasm target as well ?

**Comment by russhwolf** [comment]
@shriharsha-srb @lizhongyue248 

As [described above](https://github.com/russhwolf/multiplatform-settings/issues/142#issuecomment-1685156173), the initial wasm support didn't include the coroutines or serialization modules because the mainline kotlinx releases didn't include wasm targets. That has changed now, so I intend to add these targets in 1.2.
