### ISSUE TITLE
Error using ObservableSettings on compose multiplatform no-arg WasmJs

### ISSUE THREAD

**Issue by ronjunevaldoz** [russhwolf/multiplatform-settings#200]
```kotlin
class LocalKeyValueStorage : TokenStorage {
    private val settings: Settings by lazy { Settings() }
    private val observableSettings: ObservableSettings by lazy { settings as ObservableSettings }
    init {
        // observableSettings
    }
}
```

**Comment by russhwolf** [comment]
Not all `Settings` are `ObservableSettings`, so it's not safe to blindly cast like that.

New in 1.2.0, you can add the `multiplatform-settings-make-observable` module and do `val observableSettings = settings.makeObservable()` instead, but note that now you will only receive updates if you observe on `ObservableSettings` instance where you make changes.

Otherwise, I don't think there's anything new to add here so I'm going to close this issue.
