### ISSUE TITLE
Add support for compose

### ISSUE THREAD

**Issue by Laxystem** [russhwolf/multiplatform-settings#222]
Compose is capable of turning `Flow`s into state via `.collectAsState(initialValue = )`.

However, an instance of `Context` is required to create datastore settings on Android (as we're using *JetPack* compose), and one can only be acquired via `@Composable` functions - therefore, the following is impossible:

```kotlin
@get:Composable
expect val settings: FlowSettings

// error: @Composable invocations can only happen from the context of a @Composable function
@get:Composable
val darkMode: Boolean? by settings.getBooleanOrNullFlow("darkMode").collectAsState(initial = null)
```

**Comment by Skaldebane** [comment]
I may be missing something here, the question is a bit weird, but this code looks rather weird to me, and this library has nothing to do with _how_ you create the datastore instance (or any of the backing APIs), nor does any of this relate to Compose (whether _Jetpack_ or not) that much.

You indeed need `Context` to create the datastore, which you can then use to create the `DataStoreSettings`. How you do that is your responsibility, and depends on how you structure your project. You'll have to replace `settings` with a function that takes Context on Android (by wrapping it in some `Platform` expect class, whose Android actual stores a `context` property), and store it in your app's entry point (and maybe provide it through a composition local for ease of use).

**Comment by Laxystem** [comment]
Here's the thing, Compose allows you to gain the current context via composition locals, as you said.

I'm suggesting adding a compatibility add on with compose that'd include a syntax that works.

**Comment by russhwolf** [comment]
When you say "a syntax that works", what does that look like? 

If you want to get `Context` from a composition local, you'll need to use `@Composable` up the whole call chain for anything that touches `Settings`. If you want to do that from common you'll probably need to use Compose Multiplatform or else you can't have a composable expect in your common code. This all seems like overkill when there are plenty of non-compose ways you can get the application-level `Context` you need to create a file for DataStore.

**Comment by Skaldebane** [comment]
@Laxystem As answered by Russel himself, you just gotta do that setup yourself.
Whether you rely on Android Compose's `LocalContext` or get it some other way is up to you.

Last time I wrote a large explanation of doing this through a `Platform` class but scrapped it. If you're facing a difficulty doing this, here it is:

<details>
<summary>Explanation (click to expand)</summary>
Here's one way to go about it:

### 1. Create a `Platform` class:
```kotlin
// Platform.kt
expect class Platform
```
This is a common pattern in KMP apps, where you use this `Platform` class to store any platform-specific globals (e.g. `Context`).
#### Creating the `actual` implementations:
On Android, since you want `Context`, you'll wanna add it as a property to the `Platform` class:
```kotlin
// Platform.android.kt
actual class Platform(val context: Context)
```
On other platforms, you can leave it empty (a plain `actual class Platform`) if you don't need to pass anything.

### 2. Replace `settings` property with a `getSettings` function:
You'll wanna replace this:
```kotlin
// Settings.kt
expect val settings: FlowSettings
```
with this:
```kotlin
// Settings.kt
expect fun getSettings(platform: Platform): FlowSettings
```
passing in the `Platform`

_Note: you can also replace it with an extension property `Platform.settings` with a custom getter if you wish._

### 3. Implement the `getSettings` function:
When implementing this for Android, you'll have access to the `context` property you passed to `Platform` on Android. You can then use it to create your DataStore and then `DataStorePreferences`:
```kotlin
// Settings.android.kt
actual fun getSettings(platform: Platform): FlowSettings {
    // you can access the context you passed right here
    platform.context
	...
}
```
Other platforms' implementation can remain the same.

### 4. Create the `Platform` in your app's entry point:
On Android, this would be your `onCreate`, which will allow you to attach the current `Context`:
```kotlin
override fun onCreate(...) {
    // ...
    val platform = Platform(this) // or Platform(applicationContext)
```

### 5. Pass the `platform` instance to your UI:
There are many ways to do this.
You can either pass it as a parameter down through your composable functions, but I prefer creating a `LocalPlatform` composition local for it, similar to `LocalContext`.

#### 1) Create the composition local:
```kotlin
val LocalPlatform = staticCompositionLocalOf<Platform> { error("No LocalPlatform was provided!" }
```
_Note: I used `staticCompositionLocalOf` because this value isn't supposed to change during runtime. `LocalContext` and other composition locals pointing to long-lived objects do the same._

#### 2) Provide it in the root of your composable tree:
On Android, this would look like this
```kotlin
override fun onCreate(...) {
    // ...
    val platform = Platform(this) // or Platform(applicationContext)
    // ...
    setContent {
        CompositonLocalProvider(LocalPlatform provides platform) {
            // your UI code
        }
    }
```

### 6. Use it!
You can now use this directly from common code, and use it to create the preferences:
```kotlin
val platform = LocalPlatform.current
```
You can then store the settings instance in whatever entry point you have in common code (usually an `App` composable or something like that):
```kotlin
val platform = LocalPlatform.current
val settings = remember { getSettings(platform) }
```
Make sure to `remember` this when used inside a `@Composable`.
You can also create a `LocalSettings` for it if you wish.

### There are many ways to go about this:
This is just one way of doing things. For example you could instead opt to creating the settings instances directly in your app's entry points, and providing that, skipping the platform class (though it is useful for many things like this).

But this seems to be the most prevalent pattern in KMP apps, so there's that.
</details>

**Comment by Laxystem** [comment]
> As answered by Russel himself, you just gotta do that setup yourself.

Yes, I'm aware.

Clearly, you don't understand me, and this is not that important anyway; So I'll just close the issue.

**Comment by russhwolf** [comment]
>Clearly, you don't understand me

I'm willing to hear more if there's a need I'm not understanding. But I'm not clear what that is at the moment.

You might also find this other library helpful, either to use directly or as a reference for your own helper functions: https://github.com/burnoo/compose-remember-preference

**Comment by Laxystem** [comment]
No, it's fine, really - I might reopen this sometime with a proper explanation.
