### ISSUE TITLE
Consider changing Level of ExperimentalListener to WARNING

### ISSUE THREAD

**Issue by yshrsmz** [russhwolf/multiplatform-settings#27]
as `Level.ERROR` cannot be suppressed, and we ended up annotating every class with `ExperimentalListener` across all modules.

**Comment by russhwolf** [comment]
Yeah this is a good idea. I have the annotations there because I want to explicitly mark that API as less stable than everything else, but I also want to reduce barriers-to-entry in general because the Multiplatform ecosystem is already hard enough to get into. I'll reduce experimental annotation levels next time I do an update. 

In the meantime, you can use [`@UseExperimental`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-use-experimental/index.html) at the immediate use-site of an Experimental-annotated declaration to avoid leaking annotations up your entire call hierarchy.

**Comment by yshrsmz** [comment]
> you can use [at]UseExperimental

That's great, thanks!

**Comment by russhwolf** [comment]
Level of all experimental annotations is reduced to Warning in 0.3.2

**Comment by yshrsmz** [comment]
Thanks!
