### ISSUE TITLE
Error after clone

### ISSUE THREAD

**Issue by sebleclerc** [russhwolf/multiplatform-settings#44]
Hi!
I did a local clone of this repo and when I opened it inside IntelliJ, I had this error:

```
Build file 'multiplatform-settings/multiplatform-settings/build.gradle.kts' line: 19

An exception occurred applying plugin request [id: 'com.android.library', artifact: 'com.android.tools.build:gradle:null']
> Failed to apply plugin [id 'com.android.internal.library']
   > Your project contains 2 or more modules with the same identification com.russhwolf:multiplatform-settings
     at ":" and ":multiplatform-settings".
     You must use different identification (either name or group) for each modules.

```

Does that ring a bell?

**Comment by russhwolf** [comment]
Gradle is seeing two modules named `multiplatform-settings`, because it's both the parent folder and a module within it. Should add a `rootProject.name` in `settings.gradle.kts` so this doesn't happen. Until then you can work around by renaming the parent directory to something other that `multiplatform-settings`

**Comment by russhwolf** [comment]
I think this should be fixed now if you do a fresh clone, but let me know if you still have issues.
