### ISSUE TITLE
Put multiple values(massive/JSON) like SQL Database

### ISSUE THREAD

**Issue by Diy2210** [russhwolf/multiplatform-settings#53]
How do i save multiple values like JSON
{
 "id": "1": [
{
          "title": "Test Title",
          "url": "test.com",
          "token": 12345,
}
              [
}
I try save multipul values in one item: 
Title, Url, Token

Code:
val settings: Settings = Settings()
settings["Server"] = title + url + token
            val c: String? = settings["Server"]
            println(c)

I dont undestande how save and get it.

![Screenshot_1591865627](https://user-images.githubusercontent.com/9552501/84365535-452cb700-abda-11ea-8c72-dc9ce06bf274.png)

**Comment by russhwolf** [comment]
Multiplatform Settings is focused on saving simple, unstructured data. The easiest way to handle multiple values is to give them each separate keys.
```
settings["ServerTitle"] = title
settings["ServerUrl"] = url
settings["ServerToken"] = token
```
I've done some prototyping of an integration with kotlinx.serialization that could help automate this. That would let you define a class like
```
class Server(val title: String, val url: String, val token: String)
```
and serialize it to separate settings keys for each field. You could grab the code from #36 if you want to try it out, but I am not currently expecting to release that soon because the current implementation depends on internal APIs and doesn't work well with collections.

Another option would be to save the entire json body as a single String value, and serialize/deserialize it externally via kotlinx.serialization. I don't currently plan to expose a helper for this, but I'd be open to it if there's enough demand. Regardless, it should be pretty straightforward to do by hand if you want to go that route.

**Comment by vanniktech** [comment]
I'd just use SQLDelight.

**Comment by Diy2210** [comment]
> I'd just use SQLDelight.

SQLDelight dont work from kotlin multiplatform in common code. My app use MOKO-WIDGETS without native UI.

**Comment by vanniktech** [comment]
Of course it does
