### ISSUE TITLE
[Encryption] Provide a way for saving key-data value pairs more securely 

### ISSUE THREAD

**Issue by nrobi144** [russhwolf/multiplatform-settings#85]
Could it be possible to provide a way for saving data more securely, with encryption?

I'm thinking about [EncryptedSharedPreferences](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences) for the Android, if I'm correct `Keychain` should work on Apple targets and it's already covered somewhat, and I'm not sure about `js` targets.

@russhwolf What do you think? I could chip in with some initial research and development

**Comment by vanniktech** [comment]
Something like this? https://github.com/russhwolf/multiplatform-settings/issues/63#issuecomment-696525899

**Comment by nrobi144** [comment]
Yes, exactly. I've missed that

**Comment by russhwolf** [comment]
Yeah, for Android you can use `EncryptedSharedPreferences` already without needing any explicit library support here because it implements `SharedPreferences`. Eventually I think there will be something similar for DataStore as well, but it's not clear what that will look like yet.

For iOS (or other Apple platforms) there's `KeychainSettings`, which hasn't been very battle-tested yet but it should work (and I'd love to hear whether or not it meets your security needs). 

For JS there's nothing currently, so I'd definitely welcome contributions there. Same for other platforms.

**Comment by russhwolf** [comment]
Closing in favor of #186 which has more recent discussion on some other platform implementations
